package lancer;

import java.lang.annotation.*;

/// <h2 align="center">AutoGenerated Annotation</h2>
///
/// <p>The {@code @AutoGenerated} annotation indicates that a method was automatically
/// generated by the annotation processor during compilation.</p>
///
/// <p>This annotation is intended to document generated code, helping developers
/// understand that the method was created automatically and is not meant for
/// direct manual editing.</p>
///
/// <h3>Example Usage</h3>
/// ***
/// __before:__
/// ```java
/// @ForeignHandle(..)
/// public native void assumeInit();
/// ```
///
/// __after:__
/// ```java
/// @AutoGenerated
/// public void assumeInit() {
///     // <injected code here>
/// }
/// ```
///
/// <h3>Note</h3>
/// ***
/// <p>This annotation does not affect the behavior of the method;
/// it is purely for documentation purposes.</p>
///
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface AutoGenerated { }
